/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Visa } from "./Visa";
import { VisaCountArgs } from "./VisaCountArgs";
import { VisaFindManyArgs } from "./VisaFindManyArgs";
import { VisaFindUniqueArgs } from "./VisaFindUniqueArgs";
import { DeleteVisaArgs } from "./DeleteVisaArgs";
import { VisaService } from "../visa.service";
@graphql.Resolver(() => Visa)
export class VisaResolverBase {
  constructor(protected readonly service: VisaService) {}

  async _visasMeta(
    @graphql.Args() args: VisaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Visa])
  async visas(@graphql.Args() args: VisaFindManyArgs): Promise<Visa[]> {
    return this.service.visas(args);
  }

  @graphql.Query(() => Visa, { nullable: true })
  async visa(@graphql.Args() args: VisaFindUniqueArgs): Promise<Visa | null> {
    const result = await this.service.visa(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Visa)
  async deleteVisa(@graphql.Args() args: DeleteVisaArgs): Promise<Visa | null> {
    try {
      return await this.service.deleteVisa(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
