/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Passport } from "./Passport";
import { PassportCountArgs } from "./PassportCountArgs";
import { PassportFindManyArgs } from "./PassportFindManyArgs";
import { PassportFindUniqueArgs } from "./PassportFindUniqueArgs";
import { DeletePassportArgs } from "./DeletePassportArgs";
import { PassportService } from "../passport.service";
@graphql.Resolver(() => Passport)
export class PassportResolverBase {
  constructor(protected readonly service: PassportService) {}

  async _passportsMeta(
    @graphql.Args() args: PassportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Passport])
  async passports(
    @graphql.Args() args: PassportFindManyArgs
  ): Promise<Passport[]> {
    return this.service.passports(args);
  }

  @graphql.Query(() => Passport, { nullable: true })
  async passport(
    @graphql.Args() args: PassportFindUniqueArgs
  ): Promise<Passport | null> {
    const result = await this.service.passport(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Passport)
  async deletePassport(
    @graphql.Args() args: DeletePassportArgs
  ): Promise<Passport | null> {
    try {
      return await this.service.deletePassport(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
